ALTER TABLE medicos ADD COLUMN IF NOT EXISTS doc_identidad_url TEXT;
ALTER TABLE medicos ADD COLUMN IF NOT EXISTS doc_antecedentes_url TEXT;
ALTER TABLE medicos ADD COLUMN IF NOT EXISTS doc_residencia_url TEXT;
ALTER TABLE medicos ADD COLUMN IF NOT EXISTS docs_estado VARCHAR(20) NOT NULL DEFAULT 'pendiente';
ALTER TABLE medicos ADD COLUMN IF NOT EXISTS verificado BOOLEAN NOT NULL DEFAULT FALSE;
